##################################################################################
# Cloudify Fabric built in types and plugins definitions.
##################################################################################
plugins:
    fabric:
        executor: central_deployment_agent
        source: https://github.com/Antillion/cloudify-fabric-plugin/archive/1.2.1-ant1.zip
