#######
# Cloudify Blueprint which describes the nodecellar application
# https://github.com/ccoenraets/nodecellar
#
imports:
     -  http://www.getcloudify.org/spec/cloudify/3.0/types.yaml
     -  http://www.getcloudify.org/spec/fabric-plugin/1.0/plugin.yaml

plugins:
    nodecellar_config_plugin:
        derived_from: cloudify.plugins.agent_plugin
        properties:
            folder: nodecellar-config-plugin


types:
    pylog_app:
        derived_from: cloudify.types.fabric.app_module
        properties:
            -   transport
            -   formatter
            -   gap
            -   batch

relationships:
    nodecellar_connected_to_mongo:
        derived_from: cloudify.relationships.connected_to
        source_interfaces:
            cloudify.interfaces.relationship_lifecycle:
                - postconfigure: nodecellar_config_plugin.tasks.get_mongo_host_and_port

blueprint:
    name: elk
    nodes:
        -   name: logstash_vm
            type: cloudify.types.host
            properties:
                ip: 127.0.0.1
                cloudify_agent:
                    key: /home/vagrant/.ssh/cloudify_private_key

        -   name: elasticsearch_vm
            type: cloudify.types.host
            properties:
                ip: 127.0.0.1
                cloudify_agent:
                    key: /home/vagrant/.ssh/cloudify_private_key

        -   name: nginx
            type: cloudify.types.fabric_task.web_server
            properties:
                kibana_port: 3000
                nginx_source_repos:
                  -   deb http://nginx.org/packages/mainline/ubuntu/ precise nginx
                  -   deb-src http://nginx.org/packages/mainline/ubuntu/ precise nginx
                nginx_source_key: http://nginx.org/keys/nginx_signing.key
                nginx_config_file: configs/nginx_config_file.conf
                tasks_file: task_files/nginx_tasks.py
            relationships:
                -   target: elasticsearch_vm
                    type: cloudify.relationships.contained_in

        -   name: logstash
            type: cloudify.types.fabric_task.app_server
            properties:
                logstash_port: 999
                logstash_url: https://download.elasticsearch.org/logstash/logstash/packages/debian/logstash_1.4.2-1-2c0f5a1_all.deb
                logstash_config_file: configs/logstash_config_file.conf
                tasks_file: task_files/logstash_tasks.py
            relationships:
                -   target: logstash_vm
                    type: cloudify.relationships.contained_in

        -   name: elasticsearch
            type: cloudify.types.fabric_task.db_server
            properties:
                ip: 11.0.0.7
                elasticsearch_url: https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.2.2.deb
                tasks_file: task_files/elasticsearch_tasks.py
            relationships:
                -   target: elasticsearch_vm
                    type: cloudify.relationships.contained_in

        -   name: kibana
            type: cloudify.types.fabric_task.app_server
            properties:
                kibana_url: https://download.elasticsearch.org/kibana/kibana/kibana-3.1.0.tar.gz
                tasks_file: task_files/kibana_tasks.py
            relationships:
                -   target: elasticsearch_vm
                    type: cloudify.relationships.contained_in
                -   target: elasticsearch
                    type: cloudify.relationships.connected_to

        -   name: pylog
            type: pylog_app
            properties:
                transport: udp
                formatter: json
                gap: 1
                batch: 5
                pylog_config_file: configs/pylog_config_file.py
                tasks_file: task_files/pylog_tasks.py
            relationships:
                -   type: cloudify.relationships.contained_in
                    target: logstash_vm
                -   type: cloudify.relationships.connected_to
                    target: logstash
